version: "3"
services:
  app:
    image: node:alpine
    volumes:
      - .:/app
    working_dir: /app
    environment:
      NODE_ENV: production
      DEBUG: teochew-dictionary-backend:*
    ports:
      - 3000:3000
    command: npm run devstart_dock
    